name: Deep Learning CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Run Code Quality Checks
        run: |
          flake8 . --max-line-length=100

      - name: Run Unit Tests
        run: |
          pytest tests/

  train:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train.py

  deploy:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Model
        run: |
          echo "Deploying the trained model..."
